(define (cal a b c) 
    (- 
       (+ (* a a) (* b b ) (* c c))
       (if (<= a b) 
           (if (<= a c)
                (* a a)
                (* c c)
           )   
           (if (<= b c)
               (* b b)
               (* c c)
           )
        )
     )
)