(define (make-segment a b)
  (cons a b))
(define (start-segment x)
  (car x))
(define (end-segment x)
  (cdr x))
(define (segment-size a b)
  (sqrt (+ 
         (square (- (x-point a)
                   (x-point b)))
         (square (- (y-point a)
                   (y-point b))))))  
(define (square x)
  (* x x))

(define (make-point x y)
  (cons x y))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))

(define (midpoint-segment s)  
  (make-point (+ (x-point (start-segment s))
                 (/ (- (x-point (end-segment s))
                       (x-point (start-segment s)))
                    2))
              (+ (y-point (start-segment s))
                 (/ (- (y-point (end-segment s))
                       (y-point (start-segment s)))
                    2))))
  
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define (make-ract a b)
  (cons a b))
(define (rect-area r)
  r)
(define (rect-around r)
  r)

(define a (make-point 0 0))
(define b (make-point 2 0))
(print-point (segment-size a b))