(define (유리수-더하기 x y)
  (유리수 (+ (* (분자 x) (분모 y))
          (* (분자 y) (분모 x)))
       (* (분모 x) (분모 y))))
(define (유리수-빼기 x y)
  (유리수 (- (* (분자 x) (분모 y))
          (* (분자 y) (분모 x)))
       (* (분모 x) (분모 y))))
(define (유리수-곱하기 x y)
  (유리수 (* (분자 x) (분자 y))
       (* (분모 x) (분모 y))))
(define (유리수-나누기 x y)
  (유리수 (* (분자 x) (분모 y))
       (* (분모 x) (분자 y))))
(define (유리수 분자 분모)
  (let ((g (절대값 (최대공약수 분자 분모))))
    (cond ((> 0 분모)
           (cons (/ (* 분자 -1) g) (/ (* 분모 -1) g)))
          (else (cons (/ 분자 g) (/ 분모 g))))))
(define (분자 x)
  (car x))
(define (분모 x)
  (cdr x))
(define (유리수-보기 x)
  (newline)
  (display (분자 x))
  (display "/")
  (display (분모 x)))
(define (최대공약수 a b)
  (if (= b 0)
      a
      (최대공약수 b (remainder a b))))
(define (절대값 x)
  (if (> 0 x)
      (* x -1)
      x))